// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBijSlCRlxzMNTAIibVRnsBzXLrUm8JdMs',
    appId: '1:479745595990:web:99a73de27751f58fc079f7',
    messagingSenderId: '479745595990',
    projectId: 'smart-library-prod',
    authDomain: 'smart-library-prod.firebaseapp.com',
    storageBucket: 'smart-library-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIXEgFSV9RmYWVYOR4inzhZH4pW-00qCM',
    appId: '1:479745595990:android:7f534a9bb30f54d7c079f7',
    messagingSenderId: '479745595990',
    projectId: 'smart-library-prod',
    storageBucket: 'smart-library-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP_kwbyhsPL0Duf1bsf38On2ViW0ZaepU',
    appId: '1:479745595990:ios:fdc9e5c2ecaa6545c079f7',
    messagingSenderId: '479745595990',
    projectId: 'smart-library-prod',
    storageBucket: 'smart-library-prod.firebasestorage.app',
    iosBundleId: 'com.smartlibrary.smartLibrary',
  );
}
